### ISSUE TITLE
AppImage should bundle the ipfs binary

### ISSUE THREAD

**Issue by probonopd** [eversum/galacteek#1]
Thanks for providing an AppImage of Galacteek. Very useful!

Galacteek currently asks the user whether to download and install `./.local/share/galacteek/ipfs-bin/ipfs`. Instead, this binary could be bundled inside (and be updated together with) the AppImage.

This would be more consistent with the AppImage "one app = one file" [philosophy](https://docs.appimage.org/introduction/concepts.html), and would allow for easier checksumming and integrity verification of the code.

**Comment by eversum** [comment]
> How is the AppImage built? Is there a script that does it?
> 
> Would you be interested in having a continuous AppImage built automatically upon each `git push` using Travis CI? Might come in handy for testing.

I'll publish the build script this afternoon or a bit later :=) It uses Miniconda3 (Python3.7).

I think it would be great to have some automatic building of the image only on the master branch, if you have experience doing that that would be great help.

**Comment by eversum** [comment]
I've updated the AppImage, it now bundles go-ipfs 0.4.18 !

[https://github.com/eversum/galacteek#appimage](https://github.com/eversum/galacteek#appimage)

I've actually used an AppImage trick that you shared [here](https://discourse.appimage.org/t/call-alternative-binary-from-appimage/93/10) and adapted it. Can you try the new AppImage ?

Thanks!

**Comment by probonopd** [comment]
@eversum I like how the download link for the AppImage is an ipfs link. Eating our own dogfood ;-)

Since you are now experienced in both AppImage and ipfs, maybe you'd like to collaborate with the AppImage team:

* https://medium.com/@probonopd/is-peer-to-peer-the-solution-for-open-source-software-distribution-ae92065cbf61
* https://github.com/AppImage/AppImageKit/issues/175
* https://discuss.ipfs.io/t/ipfs-for-appimage-distribution-of-linux-applications/1553
* https://docs.appimage.org/packaging-guide/distribution.html

**Comment by probonopd** [comment]
![galacteek](https://user-images.githubusercontent.com/2480569/50552490-6c185700-0c8c-11e9-9c44-96743ab532f4.png)

:+1:  on `xubuntu-18.04-desktop-amd64.iso`.
