### ISSUE TITLE
Crashes when double-clicking an IPFS link

### ISSUE THREAD

**Issue by probonopd** [eversum/galacteek#2]
Galacteek launches but I cannot open any files:

```
me@host:~$ /home/me/Downloads/Galacteek-0.3.0-x86_64.AppImage 
Error: api not running
Error: api not running
Error: api not running
Error: api not running
Error: api not running
Error: api not running
Error: api not running
Error: api not running
Error: api not running
QXcbConnection: XCB error: 3 (BadWindow), sequence: 1956, resource id: 33643245, major code: 40 (TranslateCoords), minor code: 0
Received signal 11 SEGV_MAPERR 000000000000
#0 0x7f14ef21a9a5 <unknown>
#1 0x7f14edf5a501 <unknown>
#2 0x7f14ef21ad3d <unknown>
#3 0x7f1511c3e890 <unknown>
  r8: 0000000000000001  r9: 0000558155843b50 r10: 6f74537865546c67 r11: 00007f15119f7ec0
 r12: 000055815562c800 r13: 00005581543877b0 r14: 0000000000000000 r15: 00007f1509ac5280
  di: 0000000000001f01  si: 00007f1509ac7210  bp: 00005581557e4810  bx: 0000000000000001
  dx: 000055815562cd10  ax: 000055815562cd10  cx: 0000000000000000  sp: 00007ffc978cafd8
  ip: 0000000000000000 efl: 0000000000010206 cgf: 002b000000000033 erf: 0000000000000014
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.

me@host:~$ cat /etc/os-release 
NAME="KDE neon"
VERSION="Developer Edition"
ID=neon
ID_LIKE="ubuntu debian"
PRETTY_NAME="KDE neon Developer Edition"
VERSION_ID="18.04"
HOME_URL="http://neon.kde.org/"
SUPPORT_URL="http://neon.kde.org/"
BUG_REPORT_URL="http://bugs.kde.org/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by probonopd** [comment]
The `ipfs` daemon is running (but after a while it says it has some issue with the ports)

**Comment by probonopd** [comment]
When trying to use `$HOME/.local/share/galacteek/ipfs-bin/ipfs ` directly, it goes like this:

```
me@host:~$ /home/me/.local/share/galacteek/ipfs-bin/ipfs cat /ipfs/QmS4fTD7Rh8NouNhp9uZbawUdBpgHaUTeL3EnxX8Tiiu7H
Error: no IPFS repo found in /home/me/.ipfs.
please run: 'ipfs init'
me@host:~$ /home/me/.local/share/galacteek/ipfs-bin/ipfs cat /ipfs/QmS4fTD7Rh8NouNhp9uZbawUdBpgHaUTeL3EnxX8Tiiu7H
Error: no IPFS repo found in /home/me/.ipfs.
please run: 'ipfs init'
me@host:~$ /home/me/.local/share/galacteek/ipfs-bin/ipfs init
initializing IPFS node at /home/me/.ipfs
generating 2048-bit RSA keypair...done
peer identity: QmdvM1ExyirE2qoeFPuUX3uwQ2L6a6d9R2CW3qqh9cqvuk
to get started, enter:

        ipfs cat /ipfs/QmS4ustL54uo8FzR9455qaxZwuMiUhyvMcX9Ba8nUH4uVv/readme

me@host:~$ /home/me/.local/share/galacteek/ipfs-bin/ipfs cat /ipfs/QmS4fTD7Rh8NouNhp9uZbawUdBpgHaUTeL3EnxX8Tiiu7H
Error: merkledag: not found

```

**Comment by eversum** [comment]
> Galacteek launches but I cannot open any files:
> 
> ```
> me@host:~$ /home/me/Downloads/Galacteek-0.3.0-x86_64.AppImage 
> Error: api not running
> Error: api not running
> Error: api not running
> Error: api not running
> Error: api not running
> Error: api not running
> Error: api not running
> Error: api not running
> Error: api not running
> QXcbConnection: XCB error: 3 (BadWindow), sequence: 1956, resource id: 33643245, major code: 40 (TranslateCoords), minor code: 0
> Received signal 11 SEGV_MAPERR 000000000000
> #0 0x7f14ef21a9a5 <unknown>
> #1 0x7f14edf5a501 <unknown>
> #2 0x7f14ef21ad3d <unknown>
> #3 0x7f1511c3e890 <unknown>
>   r8: 0000000000000001  r9: 0000558155843b50 r10: 6f74537865546c67 r11: 00007f15119f7ec0
>  r12: 000055815562c800 r13: 00005581543877b0 r14: 0000000000000000 r15: 00007f1509ac5280
>   di: 0000000000001f01  si: 00007f1509ac7210  bp: 00005581557e4810  bx: 0000000000000001
>   dx: 000055815562cd10  ax: 000055815562cd10  cx: 0000000000000000  sp: 00007ffc978cafd8
>   ip: 0000000000000000 efl: 0000000000010206 cgf: 002b000000000033 erf: 0000000000000014
>  trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
> [end of stack trace]
> Calling _exit(1). Core file will not be generated.
> 
> me@host:~$ cat /etc/os-release 
> NAME="KDE neon"
> VERSION="Developer Edition"
> ID=neon
> ID_LIKE="ubuntu debian"
> PRETTY_NAME="KDE neon Developer Edition"
> VERSION_ID="18.04"
> HOME_URL="http://neon.kde.org/"
> SUPPORT_URL="http://neon.kde.org/"
> BUG_REPORT_URL="http://bugs.kde.org/"
> PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
> VERSION_CODENAME=bionic
> UBUNTU_CODENAME=bionic
> ```

Thanks for the bug report. What's the context exactly ?

When you say "double-clicking an IPFS link", is that inside a browser tab ?

I am making a new release right now with PyQt 5.11.3 and many things have been fixed with the QtWebEngine integration.

**Comment by probonopd** [comment]
For example, when I double-click on "Archives on IPFS" inside Galacteek.

**Comment by probonopd** [comment]
For example, when I double-click on "Archives on IPFS" inside Galacteek.

**Comment by probonopd** [comment]
This is no longer the case with https://ipfs.io/ipfs/Qmc9bdVkLxXmeFKZVvAEM8z69QJjoSMbU9sALtgQ7atAdU.
