### ISSUE TITLE
Have the filename in the AppImage download URL

### ISSUE THREAD

**Issue by probonopd** [eversum/galacteek#3]
This is _insanely clever._..

![galacteek](https://user-images.githubusercontent.com/2480569/50552541-6c652200-0c8d-11e9-9899-51b5dcf10e53.png)

However I think it would be nice (more human-readable) to have the filename in the AppImage download URL so that the file on disk would not look like this:

![](https://user-images.githubusercontent.com/2480569/50552546-8b63b400-0c8d-11e9-9b76-b517f9daa534.png)

I think [wrapWithDirectory](https://discuss.ipfs.io/t/adding-a-file-while-preserving-filename-using-js-ipfs/2060) a.k.a. `ipfs add -w ` can be used for this.

**Comment by eversum** [comment]
Yes of course it's not very human-readable :)

There's no perfect solution for this, you can of course wrap it with a directory i used to do that. I've thought of an intermediate solution but i prefer the current one for now.

**Comment by probonopd** [comment]
...and I always used to make fun of Flatpak

![](https://user-images.githubusercontent.com/2480569/50553000-7f302480-0c96-11e9-854f-e9a450c4cf71.jpeg)

**Comment by eversum** [comment]
The releases page now also contains links with standard AppImage filenames

**Comment by probonopd** [comment]
IPFS is way cooler ;-)

**Comment by lidel** [comment]
FYI if you add `?filename=` after CID, the gateway will respond with `content-disposition` header. It which acts as a hint for the browser how to name downloaded file :)

Try https://ipfs.io/ipfs/QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR?filename=guardian.jpg

**Comment by eversum** [comment]
Thanks @lidel, very nice trick !
