### ISSUE TITLE
Limit CPU and memory usage

### ISSUE THREAD

**Issue by probonopd** [eversum/galacteek#4]
Noticed that Galacteek (`Qmc...` process) and the `ipfs` launched by it take quite some resources. Maybe ipfs could be wrapped in `nice` so as to not use more than, say, 25% of CPU?

![resources](https://user-images.githubusercontent.com/2480569/50552724-5a857e00-0c91-11e9-8131-fc134862f255.png)

```
me@host:~$ cat /proc/meminfo 
MemTotal:        4036500 kB

me@host:~$ cat /proc/cpuinfo 
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 15
model name	: Intel(R) Core(TM)2 Duo CPU     T7300  @ 2.00GHz
```

**Comment by eversum** [comment]
The go-ipfs daemon can indeed be hungry in terms of resources especially with a high number of opened connections. There's nothing special in the way galacteek opens a subprocess for the IPFS daemon, but we could indeed limit resource usage for the process i'll try to provide a fix for that sometime soon. As for galacteek's memory usage many things can be improved for sure.

Thank you for the suggestions!

**Comment by eversum** [comment]
Starting with v0.3.3 you can now change the routing mode in the IPFS daemon settings. Using the *dhtclient* routing mode (*dht* is the default mode) will save a lot of bandwidth as you are not serving requests on the network (you're not participating in the DHT). It can also reduce CPU usage.

Latest release uses a higher *GracePeriod* by default and uses low *LowWater* and *HighWater* by default. It's also niced to priority 20 on startup.

**Comment by probonopd** [comment]
Thank you. _Much_ better now.
